--
- name: add tower project for rhel_90 workshop
  tower_project:
    name: "Workshop Project"
    organization: "Default"
    scm_type: git
    scm_url: "https://github.com/ansible/workshop-examples"
    tower_username: admin
    tower_password: "{{ admin_password }}"
    tower_host: "{{ ansible_host }}"
    tower_verify_ssl: false
