---
## re-use RHEL workshop code
- name: find ami
  include_tasks: ami_find_rhel.yml

- name: find ami for satellite
  ec2_ami_info:
    region: "{{ ec2_region }}"
    owners: "{{ ec2_info['satellite'].owners }}"
    filters:
      name: "{{ ec2_info['satellite'].filter }}"
  register: sat_amis

- name: save ami for satellite
  set_fact:
    sat_ami: >
      {{ sat_amis.images | selectattr('name', 'defined') | sort(attribute='creation_date') | last }}
