---
# region where the nodes will live
ec2_region: us-east-2
# name prefix for all the VMs
ec2_name_prefix: sean-april28-security
# amount of work benches to provision
student_total: 2
# workshop is put into isecurity mode
workshop_type: 'security'
security_console: 'qradar'
## Optional Variables
admin_password: ansible
windows_password: Ansible+Red*Hat19!20
create_login_page: false
autolicense: false
towerinstall: true
dns_type: aws
